<a href="https://colab.research.google.com/github/Priyatham1421/ai-assign1/blob/main/ai_assignment_ipy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

Task Description#1
● Use Gemini in Colab to write a function that filters out all negative numbers from a
given list

In [1]:
def filter_negative_numbers(numbers):
  """Filters out all negative numbers from a list.

  Args:
    numbers: A list of numbers.

  Returns:
    A new list containing only the non-negative numbers from the input list.
  """
  return [num for num in numbers if num >= 0]

# Example usage
my_list = [1, -2, 3, -4, 5, 0, -1]
filtered_list = filter_negative_numbers(my_list)
print(filtered_list)




[1, 3, 5, 0]


# explantaion
def filter_negative_numbers(numbers):: This line defines the function named filter_negative_numbers and indicates that it accepts one argument, numbers.
"""Docstring""": This is a docstring that explains what the function does, its arguments, and what it returns.
return [num for num in numbers if num >= 0]: This is a list comprehension. It iterates through each element (num) in the input numbers list. For each num, it checks if num is greater than or equal to 0 (if num >= 0). If the condition is true, the num is included in the new list that is being created and returned by the function.
my_list = [1, -2, 3, -4, 5, 0, -1]: This line creates a list named my_list containing both positive and negative numbers, as well as zero.
filtered_list = filter_negative_numbers(my_list): This line calls the filter_negative_numbers function with my_list as input and stores the returned filtered list in the variable filtered_list.
print(filtered_list): This line prints the contents of the filtered_list to the console.
The output [1, 3, 5, 0] confirms that the function successfully removed the negative numbers (-2, -4, and -1) from the original list

In [ ]:
Task Description#2
● Ask Gemini to generate code that reads a text file and counts the frequency of each
word. Then ask it to explain the code.

### Code Explanation

The code above performs the following steps:

1.  **Import Libraries**: It imports the `collections` module for using `Counter` (a specialized dictionary for counting hashable objects) and the `re` module for regular expressions.
2.  **Define Function `count_word_frequency`**:
    *   This function takes `file_path` as input.
    *   It initializes an empty `Counter` object called `word_counts`.
    *   It opens the specified file in read mode (`'r'`) with UTF-8 encoding to handle various characters. The `with open(...)` statement ensures the file is automatically closed even if errors occur.
    *   It iterates through each `line` in the file.
    *   For each line, it uses `re.findall(r'\b\w+\b', line.lower())` to find all words.
        *   `line.lower()` converts the line to lowercase to ensure case-insensitive counting.
        *   `re.findall(r'\b\w+\b', ...)` uses a regular expression to find sequences of word characters (`\w+`) that are bounded by word boundaries (`\b`). This helps to exclude punctuation.
    *   `word_counts.update(words)` updates the `word_counts` Counter with the words found in the current line.
    *   Finally, the function returns the `word_counts` Counter.
3.  **Example Usage**:
    *   A sample file named `sample.txt` is created with some text content.
    *   The `count_word_frequency` function is called with the path to the sample file.
    *   The returned dictionary `word_frequencies` is then iterated through, and each word and its corresponding count are printed to the console.

In [ ]:
Task Description#3
● Use Cursor AI to generate a Python class called Book with attributes title, author, and
a method summary() that prints the details.

In [3]:
import pandas as pd

# Create a dictionary with some data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

# Create a Pandas DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
print("Original DataFrame:")
display(df)

# Select a single column
print("\n'Name' column:")
display(df['Name'])

# Select rows based on a condition
print("\nPeople older than 30:")
display(df[df['Age'] > 30])

# Add a new column
df['Occupation'] = ['Engineer', 'Artist', 'Teacher', 'Doctor']
print("\nDataFrame with 'Occupation' column:")
display(df)

Original DataFrame:


Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   40     Tokyo


'Name' column:


0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object


People older than 30:


Name  Age   City
2  Charlie   35  Paris
3    David   40  Tokyo


DataFrame with 'Occupation' column:


Name  Age      City Occupation
0    Alice   25  New York   Engineer
1      Bob   30    London     Artist
2  Charlie   35     Paris    Teacher
3    David   40     Tokyo     Doctor

### Code Explanation

This code demonstrates basic operations with a Pandas DataFrame, which is a powerful data structure for working with tabular data in Python.

1.  **`import pandas as pd`**: This line imports the pandas library and assigns it the alias `pd`, which is a common convention.
2.  **`data = {...}`**: A Python dictionary is created to hold the data. The keys of the dictionary will become the column names in the DataFrame, and the values (lists) will become the column data.
3.  **`df = pd.DataFrame(data)`**: This line creates a Pandas DataFrame from the `data` dictionary.
4.  **`print("Original DataFrame:")` and `display(df)`**: These lines print a label and then display the entire DataFrame. `display()` is used in Colab for better formatting of DataFrames.
5.  **`print("\n'Name' column:")` and `display(df['Name'])`**: This shows how to select a single column from the DataFrame using square brackets with the column name.
6.  **`print("\nPeople older than 30:")` and `display(df[df['Age'] > 30])`**: This demonstrates how to filter rows based on a condition. The expression `df['Age'] > 30` creates a boolean Series, and passing this Series to the DataFrame `df[...]` selects only the rows where the condition is True.
7.  **`df['Occupation'] = [...]`**: This line adds a new column named 'Occupation' to the DataFrame. The list on the right side provides the values for the new column, and the length of the list must match the number of rows in the DataFrame.
8.  **`print("\nDataFrame with 'Occupation' column:")` and `display(df)`**: These lines display the DataFrame after the new column has been added.

In [ ]:
Task Description#4
● Ask Gemini to write a program that checks whether a number is an Armstrong
number, and then modify it using Cursor AI to improve performance or structure

# Task
write a program that checks whether a number is an Armstrong number, and then modify it using Cursor AI to improve performance or structure and explain it

## Generate initial armstrong number checking code

### Subtask:
Write a Python function to determine if a number is an Armstrong number.


**Reasoning**:
I need to write a Python function that checks if a number is an Armstrong number, following the detailed instructions provided. This involves defining a function, converting the number to a string, iterating through its digits, calculating the sum of the digits raised to the power of the number of digits, and comparing this sum to the original number.



In [4]:
def is_armstrong(number):
  """Checks if a number is an Armstrong number.

  An Armstrong number is a number that is equal to the sum of its own digits each
  raised to the power of the number of digits.

  Args:
    number: An integer to check.

  Returns:
    True if the number is an Armstrong number, False otherwise.
  """
  # Convert the number to a string to get the number of digits
  num_str = str(number)
  num_digits = len(num_str)

  sum_of_powers = 0
  # Iterate through each digit
  for digit_char in num_str:
    # Convert the digit back to an integer
    digit = int(digit_char)
    # Calculate the digit raised to the power of the number of digits
    sum_of_powers += digit ** num_digits

  # Compare the original number with the sum of powers
  return number == sum_of_powers

# Example usage
test_number = 153
if is_armstrong(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 123
if is_armstrong(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

153 is an Armstrong number.
123 is not an Armstrong number.


## Explain the initial code

### Subtask:
Provide a markdown explanation of the generated Armstrong number checking code.


**Reasoning**:
Generate a markdown explanation for the `is_armstrong` function as requested in the subtask.



In [5]:
## Code Explanation: Checking for Armstrong Numbers

This code defines a Python function called `is_armstrong` that determines whether a given integer is an Armstrong number.

An **Armstrong number** (also known as a narcissistic number, pluperfect digital invariant (PPDI), or plus perfect number) is a number that is equal to the sum of its own digits each raised to the power of the number of digits.

Here's a breakdown of how the `is_armstrong` function works:

1.  **Convert to String to Find the Number of Digits**:
    ```python
    num_str = str(number)
    num_digits = len(num_str)
    ```
    The input `number` is first converted into a string (`num_str`). This allows us to easily determine the number of digits in the number by finding the length of the string (`num_digits`).

2.  **Initialize Sum of Powers**:
    ```python
    sum_of_powers = 0
    ```
    A variable `sum_of_powers` is initialized to zero. This variable will store the sum of each digit raised to the power of the total number of digits.

3.  **Iterate Through Digits and Calculate Sum of Powers**:
    ```python
    for digit_char in num_str:
      digit = int(digit_char)
      sum_of_powers += digit ** num_digits
    ```
    The code then iterates through each character (`digit_char`) in the `num_str` (the string representation of the number). For each character:
    *   It's converted back to an integer (`digit`).
    *   This integer digit is raised to the power of `num_digits` (the total number of digits in the original number).
    *   The result is added to the `sum_of_powers`.

4.  **Compare with Original Number**:
    ```python
    return number == sum_of_powers
    ```
    Finally, the function compares the original input `number` with the calculated `sum_of_powers`. If they are equal, the number is an Armstrong number, and the function returns `True`. Otherwise, it returns `False`.

**Example Usage:**

The code includes example usage to demonstrate how to use the `is_armstrong` function:

```python
test_number = 153
if is_armstrong(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 123
if is_armstrong(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")
```
These lines call the `is_armstrong` function with `153` and `123` and print whether each number is an Armstrong number based on the function's return value.


SyntaxError: unterminated string literal (detected at line 7) (ipython-input-3086701825.py, line 7)

**Reasoning**:
The previous command failed because a markdown cell was not correctly formatted within the `code_block`. I need to output the markdown explanation as a markdown cell directly.



In [6]:
## Code Explanation: Checking for Armstrong Numbers

This code defines a Python function called `is_armstrong` that determines whether a given integer is an Armstrong number.

An **Armstrong number** (also known as a narcissistic number, pluperfect digital invariant (PPDI), or plus perfect number) is a number that is equal to the sum of its own digits each raised to the power of the number of digits.

Here's a breakdown of how the `is_armstrong` function works:

1.  **Convert to String to Find the Number of Digits**:
    ```python
    num_str = str(number)
    num_digits = len(num_str)
    ```
    The input `number` is first converted into a string (`num_str`). This allows us to easily determine the number of digits in the number by finding the length of the string (`num_digits`).

2.  **Initialize Sum of Powers**:
    ```python
    sum_of_powers = 0
    ```
    A variable `sum_of_powers` is initialized to zero. This variable will store the sum of each digit raised to the power of the total number of digits.

3.  **Iterate Through Digits and Calculate Sum of Powers**:
    ```python
    for digit_char in num_str:
      digit = int(digit_char)
      sum_of_powers += digit ** num_digits
    ```
    The code then iterates through each character (`digit_char`) in the `num_str` (the string representation of the number). For each character:
    *   It's converted back to an integer (`digit`).
    *   This integer digit is raised to the power of `num_digits` (the total number of digits in the original number).
    *   The result is added to the `sum_of_powers`.

4.  **Compare with Original Number**:
    ```python
    return number == sum_of_powers
    ```
    Finally, the function compares the original input `number` with the calculated `sum_of_powers`. If they are equal, the number is an Armstrong number, and the function returns `True`. Otherwise, it returns `False`.

**Example Usage:**

The code includes example usage to demonstrate how to use the `is_armstrong` function:

```python
test_number = 153
if is_armstrong(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 123
if is_armstrong(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")
```
These lines call the `is_armstrong` function with `153` and `123` and print whether each number is an Armstrong number based on the function's return value.


SyntaxError: unterminated string literal (detected at line 7) (ipython-input-3086701825.py, line 7)

**Reasoning**:
I am still trying to generate the markdown explanation for the `is_armstrong` function. The previous attempts failed because I was incorrectly trying to put markdown content inside a `code_block`. I need to simply output the markdown content directly.



In [7]:
%%markdown
## Code Explanation: Checking for Armstrong Numbers

This code defines a Python function called `is_armstrong` that determines whether a given integer is an Armstrong number.

An **Armstrong number** (also known as a narcissistic number, pluperfect digital invariant (PPDI), or plus perfect number) is a number that is equal to the sum of its own digits each raised to the power of the number of digits.

Here's a breakdown of how the `is_armstrong` function works:

1.  **Convert to String to Find the Number of Digits**:
    ```python
    num_str = str(number)
    num_digits = len(num_str)
    ```
    The input `number` is first converted into a string (`num_str`). This allows us to easily determine the number of digits in the number by finding the length of the string (`num_digits`).

2.  **Initialize Sum of Powers**:
    ```python
    sum_of_powers = 0
    ```
    A variable `sum_of_powers` is initialized to zero. This variable will store the sum of each digit raised to the power of the total number of digits.

3.  **Iterate Through Digits and Calculate Sum of Powers**:
    ```python
    for digit_char in num_str:
      digit = int(digit_char)
      sum_of_powers += digit ** num_digits
    ```
    The code then iterates through each character (`digit_char`) in the `num_str` (the string representation of the number). For each character:
    *   It's converted back to an integer (`digit`).
    *   This integer digit is raised to the power of `num_digits` (the total number of digits in the original number).
    *   The result is added to the `sum_of_powers`.

4.  **Compare with Original Number**:
    ```python
    return number == sum_of_powers
    ```
    Finally, the function compares the original input `number` with the calculated `sum_of_powers`. If they are equal, the number is an Armstrong number, and the function returns `True`. Otherwise, it returns `False`.

**Example Usage:**

The code includes example usage to demonstrate how to use the `is_armstrong` function:

```python
test_number = 153
if is_armstrong(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 123
if is_armstrong(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")
```
These lines call the `is_armstrong` function with `153` and `123` and print whether each number is an Armstrong number based on the function's return value.


## Code Explanation: Checking for Armstrong Numbers

This code defines a Python function called `is_armstrong` that determines whether a given integer is an Armstrong number.

An **Armstrong number** (also known as a narcissistic number, pluperfect digital invariant (PPDI), or plus perfect number) is a number that is equal to the sum of its own digits each raised to the power of the number of digits.

Here's a breakdown of how the `is_armstrong` function works:

1.  **Convert to String to Find the Number of Digits**:
    ```python
    num_str = str(number)
    num_digits = len(num_str)
    ```
    The input `number` is first converted into a string (`num_str`). This allows us to easily determine the number of digits in the number by finding the length of the string (`num_digits`).

2.  **Initialize Sum of Powers**:
    ```python
    sum_of_powers = 0
    ```
    A variable `sum_of_powers` is initialized to zero. This variable will store the sum of each digit raised to the power of the total number of digits.

3.  **Iterate Through Digits and Calculate Sum of Powers**:
    ```python
    for digit_char in num_str:
      digit = int(digit_char)
      sum_of_powers += digit ** num_digits
    ```
    The code then iterates through each character (`digit_char`) in the `num_str` (the string representation of the number). For each character:
    *   It's converted back to an integer (`digit`).
    *   This integer digit is raised to the power of `num_digits` (the total number of digits in the original number).
    *   The result is added to the `sum_of_powers`.

4.  **Compare with Original Number**:
    ```python
    return number == sum_of_powers
    ```
    Finally, the function compares the original input `number` with the calculated `sum_of_powers`. If they are equal, the number is an Armstrong number, and the function returns `True`. Otherwise, it returns `False`.

**Example Usage:**

The code includes example usage to demonstrate how to use the `is_armstrong` function:

```python
test_number = 153
if is_armstrong(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 123
if is_armstrong(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")
```
These lines call the `is_armstrong` function with `153` and `123` and print whether each number is an Armstrong number based on the function's return value.


## Modify the code

### Subtask:
Improve the performance or structure of the Armstrong number checking function.


**Reasoning**:
Refine the existing `is_armstrong` function to potentially improve its efficiency or clarity and include example usage.



In [8]:
def is_armstrong_optimized(number):
  """Checks if a number is an Armstrong number without string conversion.

  An Armstrong number is a number that is equal to the sum of its own digits each
  raised to the power of the number of digits.

  Args:
    number: An integer to check.

  Returns:
    True if the number is an Armstrong number, False otherwise.
  """
  original_number = number
  num_digits = 0
  temp_number = number

  # Count the number of digits
  while temp_number > 0:
    temp_number //= 10
    num_digits += 1

  sum_of_powers = 0
  temp_number = number # Reset temp_number for digit extraction

  # Calculate the sum of powers of digits
  while temp_number > 0:
    digit = temp_number % 10
    sum_of_powers += digit ** num_digits
    temp_number //= 10

  return original_number == sum_of_powers

# Example usage
test_number = 153
if is_armstrong_optimized(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 123
if is_armstrong_optimized(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 9474
if is_armstrong_optimized(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

153 is an Armstrong number.
123 is not an Armstrong number.
9474 is an Armstrong number.


## Explain the modified code

### Subtask:
Provide a markdown explanation of the changes made and how they improve the code.


**Reasoning**:
Create a markdown cell to explain the changes and improvements in the optimized Armstrong number checking function.



In [9]:
%%markdown
## Code Explanation: Optimized Armstrong Number Check

This section explains the modified Python function `is_armstrong_optimized` which checks if a number is an Armstrong number using a more mathematical approach, avoiding the conversion of the number to a string.

### Original vs. Optimized Approach

The original `is_armstrong` function converted the input number to a string to determine the number of digits and to iterate through each digit. While this approach is straightforward, repeatedly converting between integers and strings can introduce overhead, especially for very large numbers.

The `is_armstrong_optimized` function improves upon this by performing these operations using pure integer arithmetic:

*   **Avoiding String Conversion:** The most significant change is the removal of `str(number)` and subsequent operations on the string representation.
*   **Counting Digits Mathematically:** Instead of using `len(str(number))`, the optimized function uses a `while` loop and integer division (`// 10`) to count the digits. The loop continues as long as the `temp_number` (a copy of the original number) is greater than 0, dividing it by 10 in each iteration. Each division effectively removes the last digit, and a counter (`num_digits`) is incremented.
*   **Extracting Digits Mathematically:** To get each digit, the optimized function uses the modulo operator (`% 10`). `temp_number % 10` gives the last digit of `temp_number`. After extracting the digit, `temp_number` is updated using integer division (`// 10`) to remove the last digit for the next iteration.

### How it Works (Optimized)

1.  **Store Original Number and Initialize Variables:**
    ```python
    original_number = number
    num_digits = 0
    temp_number = number
    ```
    The original number is stored, `num_digits` is initialized to 0, and a temporary variable `temp_number` is created to avoid modifying the original input during the digit counting and extraction processes.

2.  **Count the Number of Digits:**
    ```python
    while temp_number > 0:
      temp_number //= 10
      num_digits += 1
    ```
    This `while` loop repeatedly divides `temp_number` by 10 using integer division until it becomes 0. The `num_digits` counter keeps track of how many divisions occurred, which is equal to the number of digits in the original number.

3.  **Reset Temporary Number and Initialize Sum of Powers:**
    ```python
    sum_of_powers = 0
    temp_number = number # Reset temp_number for digit extraction
    ```
    `sum_of_powers` is initialized to 0, and `temp_number` is reset to the `original_number` so that digits can be extracted from the beginning again.

4.  **Calculate the Sum of Powers of Digits:**
    ```python
    while temp_number > 0:
      digit = temp_number % 10
      sum_of_powers += digit ** num_digits
      temp_number //= 10
    ```
    This `while` loop extracts each digit from `temp_number` using the modulo operator (`% 10`), raises it to the power of `num_digits`, and adds it to `sum_of_powers`. Integer division (`// 10`) is used to remove the last digit from `temp_number` in each iteration.

5.  **Compare with Original Number:**
    ```python
    return original_number == sum_of_powers
    ```
    Finally, the calculated `sum_of_powers` is compared with the `original_number` to determine if it's an Armstrong number.

### Performance and Structural Benefits

*   **Potential Performance Improvement:** Avoiding string conversions and relying solely on integer arithmetic can be more efficient, especially for larger numbers, as mathematical operations on integers are generally faster than string manipulations.
*   **More Mathematical Structure:** The optimized code uses fundamental mathematical operations (integer division and modulo) to solve the problem, which can be considered a more elegant and potentially more performant approach for numerical tasks.

### Example Usage

The example usage remains similar to the original, demonstrating how to call the `is_armstrong_optimized` function and printing the result for test numbers, including an additional test case (9474) which is an Armstrong number.

```python
test_number = 153
if is_armstrong_optimized(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 123
if is_armstrong_optimized(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 9474
if is_armstrong_optimized(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")
```
This example usage verifies that the optimized function produces the correct output for both Armstrong and non-Armstrong numbers.


## Code Explanation: Optimized Armstrong Number Check

This section explains the modified Python function `is_armstrong_optimized` which checks if a number is an Armstrong number using a more mathematical approach, avoiding the conversion of the number to a string.

### Original vs. Optimized Approach

The original `is_armstrong` function converted the input number to a string to determine the number of digits and to iterate through each digit. While this approach is straightforward, repeatedly converting between integers and strings can introduce overhead, especially for very large numbers.

The `is_armstrong_optimized` function improves upon this by performing these operations using pure integer arithmetic:

*   **Avoiding String Conversion:** The most significant change is the removal of `str(number)` and subsequent operations on the string representation.
*   **Counting Digits Mathematically:** Instead of using `len(str(number))`, the optimized function uses a `while` loop and integer division (`// 10`) to count the digits. The loop continues as long as the `temp_number` (a copy of the original number) is greater than 0, dividing it by 10 in each iteration. Each division effectively removes the last digit, and a counter (`num_digits`) is incremented.
*   **Extracting Digits Mathematically:** To get each digit, the optimized function uses the modulo operator (`% 10`). `temp_number % 10` gives the last digit of `temp_number`. After extracting the digit, `temp_number` is updated using integer division (`// 10`) to remove the last digit for the next iteration.

### How it Works (Optimized)

1.  **Store Original Number and Initialize Variables:**
    ```python
    original_number = number
    num_digits = 0
    temp_number = number
    ```
    The original number is stored, `num_digits` is initialized to 0, and a temporary variable `temp_number` is created to avoid modifying the original input during the digit counting and extraction processes.

2.  **Count the Number of Digits:**
    ```python
    while temp_number > 0:
      temp_number //= 10
      num_digits += 1
    ```
    This `while` loop repeatedly divides `temp_number` by 10 using integer division until it becomes 0. The `num_digits` counter keeps track of how many divisions occurred, which is equal to the number of digits in the original number.

3.  **Reset Temporary Number and Initialize Sum of Powers:**
    ```python
    sum_of_powers = 0
    temp_number = number # Reset temp_number for digit extraction
    ```
    `sum_of_powers` is initialized to 0, and `temp_number` is reset to the `original_number` so that digits can be extracted from the beginning again.

4.  **Calculate the Sum of Powers of Digits:**
    ```python
    while temp_number > 0:
      digit = temp_number % 10
      sum_of_powers += digit ** num_digits
      temp_number //= 10
    ```
    This `while` loop extracts each digit from `temp_number` using the modulo operator (`% 10`), raises it to the power of `num_digits`, and adds it to `sum_of_powers`. Integer division (`// 10`) is used to remove the last digit from `temp_number` in each iteration.

5.  **Compare with Original Number:**
    ```python
    return original_number == sum_of_powers
    ```
    Finally, the calculated `sum_of_powers` is compared with the `original_number` to determine if it's an Armstrong number.

### Performance and Structural Benefits

*   **Potential Performance Improvement:** Avoiding string conversions and relying solely on integer arithmetic can be more efficient, especially for larger numbers, as mathematical operations on integers are generally faster than string manipulations.
*   **More Mathematical Structure:** The optimized code uses fundamental mathematical operations (integer division and modulo) to solve the problem, which can be considered a more elegant and potentially more performant approach for numerical tasks.

### Example Usage

The example usage remains similar to the original, demonstrating how to call the `is_armstrong_optimized` function and printing the result for test numbers, including an additional test case (9474) which is an Armstrong number.

```python
test_number = 153
if is_armstrong_optimized(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 123
if is_armstrong_optimized(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number = 9474
if is_armstrong_optimized(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")
```
This example usage verifies that the optimized function produces the correct output for both Armstrong and non-Armstrong numbers.


## Summary:

### Data Analysis Key Findings

*   The initial code successfully identified 153 as an Armstrong number and 123 as not an Armstrong number.
*   The optimized code, `is_armstrong_optimized`, which avoids string conversion, also correctly identified 153 and 9474 as Armstrong numbers and 123 as not an Armstrong number.

### Insights or Next Steps

*   The optimized approach using mathematical operations (integer division and modulo) is generally more efficient for numerical tasks compared to string conversions, especially for larger numbers.
*   Consider benchmarking the performance difference between the two approaches for various input sizes to quantify the improvement.


In [ ]:
Task Description#5
● Use both Gemini and Cursor AI to generate code for sorting a list of dictionaries by a
specific key (e.g., age)

In [10]:
# Sample list of dictionaries
list_of_dicts = [
    {'name': 'Alice', 'age': 30},
    {'name': 'Bob', 'age': 25},
    {'name': 'Charlie', 'age': 35},
    {'name': 'David', 'age': 20}
]

# Sort the list of dictionaries by the 'age' key
sorted_list = sorted(list_of_dicts, key=lambda x: x['age'])

# Print the sorted list
print("Sorted list by age:")
print(sorted_list)

# Sort the list of dictionaries by the 'name' key
sorted_list_by_name = sorted(list_of_dicts, key=lambda x: x['name'])

# Print the list sorted by name
print("\nSorted list by name:")
print(sorted_list_by_name)

Sorted list by age:
[{'name': 'David', 'age': 20}, {'name': 'Bob', 'age': 25}, {'name': 'Alice', 'age': 30}, {'name': 'Charlie', 'age': 35}]

Sorted list by name:
[{'name': 'Alice', 'age': 30}, {'name': 'Bob', 'age': 25}, {'name': 'Charlie', 'age': 35}, {'name': 'David', 'age': 20}]


### Code Explanation

This code demonstrates how to sort a list of dictionaries in Python based on the value of a specific key within each dictionary.

1.  **`list_of_dicts = [...]`**: This line creates a sample list where each element is a dictionary. Each dictionary represents a person with 'name' and 'age' keys.
2.  **`sorted(list_of_dicts, key=lambda x: x['age'])`**: This is the core of sorting the list by age.
    *   `sorted()`: This is a built-in Python function that returns a new sorted list from the items in an iterable.
    *   `list_of_dicts`: This is the list of dictionaries that we want to sort.
    *   `key=lambda x: x['age']`: This is the crucial part for sorting by a specific key.
        *   `key`: This argument specifies a function of one argument that is used to extract a comparison key from each list element.
        *   `lambda x: x['age']`: This is a small anonymous function (a lambda function). It takes one argument, `x` (which represents each dictionary in the `list_of_dicts` during the sorting process), and returns the value associated with the key `'age'` from that dictionary (`x['age']`). The `sorted()` function then uses these 'age' values to determine the order of the dictionaries in the sorted list.
3.  **`sorted_list = ...`**: The result of the sorting (the new sorted list) is stored in the `sorted_list` variable.
4.  **`print("Sorted list by age:")` and `print(sorted_list)`**: These lines print a label and then the contents of the `sorted_list` to show the result of sorting by age.
5.  **`sorted(list_of_dicts, key=lambda x: x['name'])`**: This line is similar to the previous sorting step, but this time the `key` is `lambda x: x['name']`, which means the list will be sorted based on the values associated with the 'name' key in each dictionary.
6.  **`sorted_list_by_name = ...`**: The list sorted by name is stored in the `sorted_list_by_name` variable.
7.  **`print("\nSorted list by name:")` and `print(sorted_list_by_name)`**: These lines print a label and the contents of the `sorted_list_by_name` to show the result of sorting by name.